apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fullname" . }}-post-delete-hook
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels: {{ include "labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: remove-finalizers
          image: {{ .Values.postDeleteJob.image.repository }}:{{ default .Values.global.chart.appVersion .Values.postDeleteJob.image.tag }}
                {{- with .Values.postDeleteJob.image.pullPolicy }}
          imagePullPolicy: {{ . }}
                {{- end }}
                {{- with .Values.postDeleteJob.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
      serviceAccountName: {{ include "fullname" . }}-post-delete-hook
            {{- with .Values.postDeleteJob.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ . }}
            {{- end }}
            {{- with .Values.postDeleteJob.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.postDeleteJob.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.postDeleteJob.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.postDeleteJob.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
        {{- end }}
