apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fullname" . }}
webhooks:
  - clientConfig:
      caBundle: Cg==
            {{- if .Values.global.debug }}
      url: "https://172.17.0.1:{{ .Values.webhook.port }}/mutate-v1-pod"
            {{- else }}
      service:
        name: {{ include "fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-v1-pod
          {{- end }}
    failurePolicy: Fail
    name: {{ include "fullname" . }}.multicluster.admiralty.io
    namespaceSelector:
      matchLabels:
        multicluster-scheduler: enabled
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
