apiVersion: v2
name: multicluster-scheduler
version: 0.9.3
#kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A system of Kubernetes controllers that intelligently schedules workloads across clusters.
type: application
#keywords:
#  - A list of keywords about this project (optional)
home: https://github.com/admiraltyio/multicluster-scheduler
#sources:
#  - https://github.com/admiraltyio/multicluster-scheduler
#maintainers: # (optional)
#  - name: The maintainer's name (required for each maintainer)
#    email: The maintainer's email (optional for each maintainer)
#    url: A URL for the maintainer (optional for each maintainer)
icon: https://admiralty.io/icons/icon-144x144.png
appVersion: 0.9.3
#deprecated: Whether this chart is deprecated (optional, boolean)
